name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build dep
      run: sudo apt install bison flex libelf-dev
    - name: Run Script to Create Minimal x86_64 iso
      run: |
        ./build_linux.sh
